// API calls for VeriText services

const PLAGIARISM_API_URL = "https://rapakarohith-veritext-backend.hf.space/api/plagiarism-check";
const AI_DETECT_API_URL = "https://rapakarohith-veritext-backend.hf.space/api/ai-detect";

export interface PlagiarismMatch {
  text: string;
  similarity: number;
}

export interface PlagiarismResult {
  similarity: number;
  matches: PlagiarismMatch[];
  wordCount: number;
  sentenceCount: number;
}

// helper delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

export async function checkPlagiarism(text: string): Promise<PlagiarismResult> {

  const MAX_RETRIES = 5;

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {

    try {

      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 20000);

      const response = await fetch(PLAGIARISM_API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
        signal: controller.signal
      });

      clearTimeout(timeout);

      // backend waking up (Render cold start)
      if (response.status === 503) {
        console.warn("Backend warming up... retrying");
        await delay(3000);
        continue;
      }

      if (!response.ok) {
        throw new Error(`Server error: ${response.status}`);
      }

      const data = await response.json();

      // backend returns { results: [...] }
      const matches: PlagiarismMatch[] = (data.results || []).map(
        (m: { matched_text: string; similarity_score: number }) => ({
          text: m.matched_text,
          similarity: Math.round(m.similarity_score * 100)
        })
      );

      const wordCount = text.split(/\s+/).filter(Boolean).length;

      const sentenceCount =
        text.split(/(?<=[.!?])\s+/).filter(s => s.trim().length > 0).length || 1;

      const similarity =
        matches.length > 0
          ? Math.round(matches.reduce((sum, m) => sum + m.similarity, 0) / matches.length)
          : 0;

      return {
        similarity,
        matches,
        wordCount,
        sentenceCount
      };

    } catch (err) {

      if (attempt === MAX_RETRIES - 1) {
        console.error("Plagiarism API failed:", err);
        throw new Error("Plagiarism server unavailable. Please try again.");
      }

      await delay(2000);
    }
  }

  throw new Error("Backend unavailable");
}



export interface ComparisonResult {
  similarity: number;
  differences: { type: 'addition' | 'deletion' | 'change'; text: string; position: number }[];
  doc1Lines: string[];
  doc2Lines: string[];
}



export interface AIDetectionResult {
  aiProbability: number;
  sentences: { text: string; probability: number; suspicious: boolean }[];
}



export async function compareDocuments(doc1: string, doc2: string): Promise<ComparisonResult> {

  await delay(2000);

  const doc1Lines = doc1.split('\n').filter(l => l.trim());
  const doc2Lines = doc2.split('\n').filter(l => l.trim());

  return {
    similarity: 67,
    differences: [
      { type: 'change', text: 'Modified introduction paragraph', position: 0 },
      { type: 'addition', text: 'New methodology section added', position: 3 },
      { type: 'deletion', text: 'Removed conclusion remarks', position: 5 }
    ],
    doc1Lines,
    doc2Lines
  };
}



export async function detectAI(text: string): Promise<AIDetectionResult> {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY || localStorage.getItem('gemini_api_key');
  
  if (!apiKey) {
    throw new Error("Missing Gemini API Key. Please configure it in your settings or .env file.");
  }

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: `You are an AI detection system. Analyze the following text and determine the probability (0-100) that it was generated by an AI (like ChatGPT, Claude, etc). 
Return ONLY a valid JSON object strictly adhering to this format, no markdown blocks, no other text:
{
  "overall": <number 0-100>,
  "sentences": [
    { "text": "<exact sentence>", "probability": <number 0-100> }
  ]
}

Text to analyze:
${text}`
                }
              ]
            }
          ],
          generationConfig: {
            temperature: 0.1,
            responseMimeType: "application/json"
          }
        }),
      }
    );

    if (!response.ok) {
      const err = await response.json().catch(() => ({}));
      throw new Error(err?.error?.message || `AI Detection failed with status: ${response.status}`);
    }

    const resultData = await response.json();
    const candidateText = resultData?.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!candidateText) {
      throw new Error("Invalid response format from Gemini API");
    }

    const data = JSON.parse(candidateText);

    return {
      aiProbability: Math.round(data.overall || 0),
      sentences: (data?.sentences || []).map((s: any) => ({
        text: s.text || "",
        probability: Math.round(s.probability || 0),
        suspicious: (s.probability || 0) > 60
      }))
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new Error(`Unable to analyze AI probability: ${msg}`);
  }
}
